import {getInterfaceBounds, labelOverlapsInterface, onInterfaceChange} from './ui.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import DATA from '../data/campus.geojson';
import {createLandmark} from './landmarks.js';
import {createCulturalLandmark} from './cultural-landmarks.js';

export function startXueyuan(){
const $=s=>document.querySelector(s), mobile=()=>innerWidth<701;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const origin=[116.34565,39.9790], extent=[-1000,-730,190,390];
const xy=c=>[(c[0]-origin[0])*111319.49*Math.cos(origin[1]*Math.PI/180),-(c[1]-origin[1])*111319.49];
const inside=([x,z],r=0)=>x>extent[0]+r&&x<extent[2]-r&&z>extent[1]+r&&z<extent[3]-r;
const data=DATA.features.map(f=>({...f,p:f.properties,rings:f.geometry.type==='Polygon'?f.geometry.coordinates.map(r=>r.map(xy)):null,line:f.geometry.type==='LineString'?f.geometry.coordinates.map(xy):null}));
let seed=931;function rand(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;}
function clip(poly){let p=poly.slice();for(const [axis,bound,greater]of [[0,extent[0],true],[0,extent[2],false],[1,extent[1],true],[1,extent[3],false]]){let out=[];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],ai=greater?a[axis]>=bound:a[axis]<=bound,bi=greater?b[axis]>=bound:b[axis]<=bound;if(ai)out.push(a);if(ai!==bi){const t=(bound-a[axis])/(b[axis]-a[axis]);out.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]);}}p=out;}return p;}
function pointIn(p,poly){let v=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))v=!v;}return v;}
function centroid(poly){const p=poly.slice(0,-1);return [p.reduce((s,v)=>s+v[0],0)/p.length,p.reduce((s,v)=>s+v[1],0)/p.length];}
function distanceSegment(p,a,b){const vx=b[0]-a[0],vz=b[1]-a[1];const t=THREE.MathUtils.clamp(((p[0]-a[0])*vx+(p[1]-a[1])*vz)/(vx*vx+vz*vz||1),0,1);return Math.hypot(p[0]-a[0]-vx*t,p[1]-a[1]-vz*t);}
let renderer,scene,camera,controls;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});}catch(e){$('#loading p').textContent='浏览器未能启用 WebGL，请使用支持硬件加速的 Chrome 或 Edge 打开。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('#scene').append(renderer.domElement);
scene=new THREE.Scene();scene.background=new THREE.Color('#e8ede8');scene.fog=new THREE.Fog('#e8ede8',3500,8500);
camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,1,12000);
controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=95;controls.maxDistance=5500;controls.maxPolarAngle=Math.PI/2-.12;controls.minPolarAngle=.02;controls.target.set(-45,0,-5);controls.enablePan=true;controls.screenSpacePanning=false;controls.zoomSpeed=.85;controls.rotateSpeed=.55;controls.autoRotateSpeed=.5;
const hemi=new THREE.HemisphereLight('#e4f1ff','#9b9e78',2.8);scene.add(hemi);
const sun=new THREE.DirectionalLight('#fff1cd',3.2);sun.position.set(-230,480,250);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-1550,right:950,top:1500,bottom:-1200,near:1,far:4500});sun.shadow.bias=-.00015;sun.shadow.normalBias=.5;sun.shadow.radius=3;scene.add(sun);
const fill=new THREE.DirectionalLight('#d3e4ee',.4);fill.position.set(200,120,-300);scene.add(fill);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.88,metalness:0,...extra});
const materials={stone:mat('#d8d6c5'),main:mat('#dddccf'),roof:mat('#bcc4bd'),glass:mat('#4c686a',{roughness:.35,metalness:.2}),window:mat('#456265',{roughness:.42,metalness:.1}),lit:mat('#668284',{roughness:.4,emissive:'#ffc777',emissiveIntensity:0}),trim:mat('#edefe1'),road:mat('#bac4ba'),path:mat('#deded0'),grass:mat('#a9bd91'),lawn:mat('#99b382'),green:mat('#a8bf96'),trunk:mat('#827e60'),tree:mat('#708d5c'),treeLight:mat('#91a975'),lamp:mat('#e5deae',{emissive:'#ffc575',emissiveIntensity:.1}),base:mat('#d8dccf')};
function box(w,h,d,x,y,z,m,parent=scene){const obj=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);obj.position.set(x,y+h/2,z);obj.castShadow=true;obj.receiveShadow=true;parent.add(obj);return obj;}
function shapeGeo(rings,h=0){const p=clip(rings[0]);if(p.length<3)return null;const shape=new THREE.Shape(p.map(([x,z])=>new THREE.Vector2(x,-z)));for(const hole of rings.slice(1)){shape.holes.push(new THREE.Path(hole.map(([x,z])=>new THREE.Vector2(x,-z))));}const geo=h?new THREE.ExtrudeGeometry(shape,{depth:h,bevelEnabled:false,steps:1}):new THREE.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);return geo;}
function polyMesh(rings,h,y,m,parent=scene){const g=shapeGeo(rings,h);if(!g)return null;const mesh=new THREE.Mesh(g,m);mesh.position.y=y;mesh.receiveShadow=true;mesh.castShadow=h>1;parent.add(mesh);return mesh;}
box(1190,9,1120,-405,-9,-170,materials.base);
box(1190,.65,1120,-405,0,-170,materials.green);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(8000,8000),mat('#e8ede8'));floor.rotation.x=-Math.PI/2;floor.position.y=-9.1;floor.receiveShadow=true;scene.add(floor);
const greenAreas=[];
for(const f of data){if(!f.rings||f.p.building&&f.p.leisure!=='park')continue;if(f.p.leisure==='park'||f.p.landuse==='grass'||f.p.landuse==='forest'||f.p.natural==='wood'){polyMesh(f.rings,.15,.7,materials.lawn);greenAreas.push(f.rings[0]);}else if(f.p.natural==='water')polyMesh(f.rings,0,1.03,mat('#87b2ac',{roughness:.28}));}
const mainOutline=data.find(f=>f.p.name==='新主楼'&&f.p.osm_type==='relation');
if(mainOutline)polyMesh([mainOutline.rings[0]],1,.65,materials.path);
// 在真实内院范围内构造简化花坛；几何来自设计布置，不作为实测景观。
for(const [x,z,w,d]of [[-52,-23,27,29],[45,-25,26,28],[-48,50,32,30],[42,53,32,27]]){box(w,.45,d,x,1.6,z,materials.lawn);}
const roads=[];const roadGeo=[],pathGeo=[];
function lineRibbon(line,width,y,bucket){for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.01)continue;let nx=-dz/len*width/2,nz=dx/len*width/2;let p=clip([[a[0]+nx,a[1]+nz],[b[0]+nx,b[1]+nz],[b[0]-nx,b[1]-nz],[a[0]-nx,a[1]-nz]]);if(p.length<3)continue;const g=shapeGeo([p]);g.translate(0,y,0);bucket.push(g);}}
for(const f of data){if(!f.p.highway||f.p.tunnel==='yes'||Number(f.p.layer)<0)continue;const line=f.line||f.rings?.[0];if(!line)continue;const pedestrian=['footway','path','steps','pedestrian','cycleway'].includes(f.p.highway);let width=Number(f.p.width)||(pedestrian?(f.p.highway==='pedestrian'?7:2.5):f.p.highway==='primary'?14:f.p.highway==='secondary'?10:6);width=Math.min(width,20);roads.push({line,width,pedestrian});if(f.rings)polyMesh(f.rings,0,.9,materials.path);else lineRibbon(line,width,pedestrian?.92:.86,pedestrian?pathGeo:roadGeo);}
function mergeBatch(geos,material){if(!geos.length)return;const g=mergeGeometries(geos,false);const mesh=new THREE.Mesh(g,material);mesh.receiveShadow=true;scene.add(mesh);geos.forEach(g=>g.dispose());return mesh;}
mergeBatch(roadGeo,materials.road);mergeBatch(pathGeo,materials.path);
const sportRed=mat('#b77e69'),sportGreen=mat('#739c81'),sportBlue=mat('#6d9696');
for(const f of data){if(!f.rings||!['pitch','track','playground'].includes(f.p.leisure))continue;const ring=f.rings[0];if(f.p.leisure==='track'){const oval=f.rings[1]||ring;polyMesh([oval],.12,1,sportRed);const cx=oval.reduce((a,p)=>a+p[0],0)/oval.length,cz=oval.reduce((a,p)=>a+p[1],0)/oval.length;polyMesh([oval.map(([x,z])=>[cx+(x-cx)*.77,cz+(z-cz)*.85])],.05,1.14,sportGreen);for(const k of [.83,.9,.97]){const ps=oval.map(([x,z])=>[cx+(x-cx)*k,cz+(z-cz)*(.85+(k-.77)*.65)]);const lines=[];lineRibbon(ps,.16,1.21,lines);mergeBatch(lines,materials.trim);}}else{polyMesh(f.rings,.08,1,f.p.sport==='soccer'?sportGreen:sportBlue);const xs=ring.map(p=>p[0]),zs=ring.map(p=>p[1]),a=Math.min(...xs)+1,b=Math.max(...xs)-1,c=Math.min(...zs)+1,d=Math.max(...zs)-1;if(b-a>5&&d-c>5){const lines=[];lineRibbon([[a,c],[b,c],[b,d],[a,d],[a,c]],.14,1.12,lines);lineRibbon([[a,(c+d)/2],[b,(c+d)/2]],.14,1.12,lines);mergeBatch(lines,materials.trim);}}}

const heritageMat=mat('#d0bc93'),housingMat=mat('#c8c2b0');
const buildings=[],pickables=[],windowGeos=[],litGeos=[],trimGeos=[];
const heights={'主楼':23,'主北':19,'主南':19,'主M':17,'北航图书馆':24,'北航世宁大厦':60,'柏彦大厦':56,'致真大厦':72,'体育馆':17,'游泳馆':13,'天行网球馆':11,'晨兴音乐厅':18,'北京航空航天博物馆':24,'唯实大厦':65,'新主楼会议中心':7.2,'第十馆':14,'九号楼（原培训中心）':23};
function facade(ring,h,base,main=false){const poly=ring;for(let i=1;i<poly.length;i++){const a=poly[i-1],b=poly[i],dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz);if(l<5)continue;const n=Math.floor(l/(main?4.1:5)),step=l/(n+1),angle=-Math.atan2(dz,dx),floors=Math.max(1,Math.round(h/3.6));for(let j=1;j<=n;j++){let x=a[0]+dx*j/(n+1),z=a[1]+dz*j/(n+1);for(let k=0;k<floors;k++){const g=new THREE.BoxGeometry(step*.58,Math.min(2.1,h/floors*.6),.20);g.rotateY(angle);g.translate(x,base+1.4+k*(h/floors),z);(rand()<.24?litGeos:windowGeos).push(g);}if(main&&j%3===0){const g=new THREE.BoxGeometry(.48,h+.3,.7);g.rotateY(angle);g.translate(x,base+h/2,z);trimGeos.push(g);}}}}
for(const f of data){if(!f.p.building||!f.rings||['park','pitch','track','playground'].includes(f.p.leisure)||Number(f.p.layer)<0||Number(f.p.level)<0)continue;const ring=clip(f.rings[0]);if(ring.length<3)continue;let c=centroid(f.rings[0]);if(!inside(c,4))continue;
 let name=f.p.name||'未命名建筑';if(name==='培训中心')name='九号楼（原培训中心）';if(/^学生?\d+公寓$/.test(name)||/^\d+公寓$/.test(name))name='学生'+name.replace('学生','');if(/^way\/7395203(08|09|10|11|12|13|16|17|18)$/.test(f.id)||f.id==='way/485050586')name='大运村'+name;const main=/新主楼/.test(name);let height=main&&name!=='新主楼会议中心'?39.6:heights[name]||(+f.p['building:levels']||0)*3.4||(/公寓/.test(name)?22:/住宅/.test(name)?18:16);if(f.p.height)height=parseFloat(f.p.height)||height;
 const custom=createLandmark(name,f.rings)||createCulturalLandmark(name,[ring]);if(custom){scene.add(custom.mesh);const b={id:f.id,name,main:false,rings:f.rings,...custom};buildings.push(b);custom.mesh.traverse(o=>{if(o.isMesh)o.userData.building=b;});pickables.push(custom.mesh);continue;}
 const heritage=['主楼','主北','主南','主M','一号楼','二号楼','三号楼','四号楼'].includes(name);let material=main?materials.main:heritage?heritageMat:/公寓|住宅/.test(name)?housingMat:materials.stone;const mesh=polyMesh(f.rings,height,1,material);if(!mesh)continue;const b={id:f.id,name,center:c,height,main,mesh,rings:f.rings,source:f.p.height?'地图标注楼高':f.p['building:levels']?'楼高由地图层数估算':main&&name!=='新主楼会议中心'?'参考整体 11 层，楼高约 39.6 m（估算）':'高度为展示估算，待校核'};buildings.push(b);mesh.userData.building=b;pickables.push(mesh);
 polyMesh(f.rings,.55,height+1,materials.roof);facade([...ring,ring[0]],height,1,main);
 if(heritage){for(const y of [height-1,height+.3]){const cornice=polyMesh(f.rings,.4,y,materials.trim);cornice.userData.building=b;}b.description='按地图保留老教学楼群轮廓与院落；浅色立面和层叠檐口参考北航公开照片，窗格、楼高及屋面细节为简化估算。';b.source='OSM 轮廓＋北航总务部改造资料；高度约 '+height+' m（估算）';}
 if(main){let minX=Math.min(...ring.map(v=>v[0])),maxX=Math.max(...ring.map(v=>v[0])),minZ=Math.min(...ring.map(v=>v[1])),maxZ=Math.max(...ring.map(v=>v[1]));for(let j=0;j<2;j++){const rx=c[0]+(j-.5)*Math.min(14,(maxX-minX)*.2),rz=c[1];if(pointIn([rx,rz],ring))box(5,1.7,4,rx,height+1.5,rz,materials.roof);}}
}
for(const b of buildings.filter(b=>b.landmark)){const batches=new Map();b.mesh.updateMatrixWorld(true);for(const child of [...b.mesh.children]){if(!child.isMesh||Array.isArray(child.material))continue;const g=child.geometry.clone();child.updateMatrix();g.applyMatrix4(child.matrix);g.deleteAttribute('uv');const key=child.material;if(!batches.has(key))batches.set(key,[]);batches.get(key).push(g);b.mesh.remove(child);child.geometry.dispose();}for(const [material,geos]of batches){const g=mergeGeometries(geos.map(x=>x.index?x.toNonIndexed():x),false);if(!g)continue;const m=new THREE.Mesh(g,material);m.castShadow=m.receiveShadow=true;m.userData.building=b;b.mesh.add(m);geos.forEach(x=>x.dispose());}}
// 北侧 H 座/架空连接：以 A、G 座之间的真实空隙定位，尺寸参考照片估计。
const northBridge=[[-43,-72],[29,-74],[29,-44],[-43,-42],[-43,-72]];
const bridge=polyMesh([northBridge],9,31.6,materials.main);facade(northBridge,9,31.6,true);
const bridgeBuilding={id:'interpretive/north-bridge',name:'新主楼北侧架空连接',center:[-7,-57],height:40.6,main:true,mesh:bridge,source:'照片参考重建 · 跨度、净高与层数均为估算'};bridge.userData.building=bridgeBuilding;pickables.push(bridge);
box(70,.8,30,-7,40.6,-58,materials.roof);
// 内院会议中心与步行联系的简化表达。
box(6,3,35,0,1,-56,materials.path);box(6,3,35,0,1,44,materials.path);
for(let i=0;i<9;i++)box(24,.32*(i+1),2.2,-6,1,-87+i*2.2,materials.path);
for(const [x,z,w,d]of [[-76,-41,9,9],[66,-37,9,9],[-72,53,9,9],[65,51,9,9]])box(w,.6,d,x,1,z,materials.path);
mergeBatch(windowGeos,materials.window);mergeBatch(litGeos,materials.lit);mergeBatch(trimGeos,materials.trim);
// 树木仅做景观表达，避让原始建筑和道路，不声称逐棵位置真实。
const treePositions=[];
function validTree(p){return inside(p,8)&&!data.some(f=>f.rings&&(['pitch','track','playground'].includes(f.p.leisure)||f.p.natural==='water')&&pointIn(p,f.rings[0]))&&!buildings.some(b=>b.viewFromSouth&&Math.abs(p[0]-b.center[0])<18&&p[1]>Math.max(...b.rings[0].map(v=>v[1]))-1&&p[1]<Math.max(...b.rings[0].map(v=>v[1]))+9)&&!buildings.some(b=>b.landmark&&!b.viewFromSouth&&Math.abs(p[0]-b.center[0])<48&&p[1]>b.center[1]-60&&p[1]<b.center[1]-30)&&!buildings.some(b=>pointIn(p,b.rings[0])||b.rings[0].some((a,i,ar)=>distanceSegment(p,a,ar[(i+1)%ar.length])<3))&&!roads.some(r=>r.line.some((a,i,ar)=>i>0&&distanceSegment(p,ar[i-1],a)<r.width/2+2))&&!treePositions.some(t=>Math.hypot(t[0]-p[0],t[1]-p[1])<5);}
for(const r of roads){if(r.pedestrian)continue;for(let i=1;i<r.line.length;i++){const a=r.line[i-1],b=r.line[i],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<8)continue;for(let d=5;d<len;d+=12){for(const side of [-1,1]){const offset=r.width/2+5;let p=[a[0]+dx*d/len-dz/len*offset*side,a[1]+dz*d/len+dx/len*offset*side];if(validTree(p))treePositions.push(p);}}}}
for(let i=0;i<6000;i++){let p=[extent[0]+rand()*1190,extent[1]+rand()*1120];const inMain=mainOutline&&pointIn(p,mainOutline.rings[0]);if(inMain&&!greenAreas.some(g=>pointIn(p,g)))continue;if(validTree(p)&&rand()<.2)treePositions.push(p);}
for(const [cx,cz]of [[-52,-23],[45,-25],[-48,50],[42,53]]){for(let i=0;i<4;i++){let p=[cx+(i%2-.5)*14,cz+(Math.floor(i/2)-.5)*14];if(validTree(p))treePositions.push(p);}}
const crowns=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),materials.tree,treePositions.length),trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.45,.65,1,5),materials.trunk,treePositions.length);const dummy=new THREE.Object3D();
treePositions.forEach(([x,z],i)=>{const size=3.2+rand()*1.8;dummy.position.set(x,5+size*.4,z);dummy.scale.set(size,size*1.1,size);dummy.rotation.set(rand()*.4,rand()*6,.1);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix);crowns.setColorAt(i,new THREE.Color().setHSL(.22+rand()*.06,.20+rand()*.13,.32+rand()*.16));dummy.position.set(x,2.5,z);dummy.scale.set(1,4,1);dummy.rotation.set(0,0,0);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);});crowns.castShadow=true;crowns.receiveShadow=true;scene.add(crowns,trunks);
const lamps=[];for(const z of [-109,103])for(let x=-107;x<=100;x+=28)lamps.push([x,z]);for(const [x,z]of lamps){box(.28,5,.28,x,1,z,materials.trunk);box(1.5,.35,1.5,x,6,z,materials.lamp);}
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=64;const gc=glowCanvas.getContext('2d');const gr=gc.createRadialGradient(32,32,1,32,32,30);gr.addColorStop(0,'rgba(255,207,119,.8)');gr.addColorStop(1,'rgba(255,207,119,0)');gc.fillStyle=gr;gc.fillRect(0,0,64,64);const glowMat=new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending});for(const [x,z]of lamps){const m=new THREE.Mesh(new THREE.PlaneGeometry(17,17),glowMat);m.rotation.x=-Math.PI/2;m.position.set(x,1.85,z);scene.add(m);}
// 地名保持少量常驻，其他建筑可通过点击或下拉框查看。
const labelSpecs=[{name:'新主楼',center:[-6,-57],height:43,primary:true},...['主楼','北航图书馆','学生13公寓','学生15公寓','合一楼','体育馆','晨兴音乐厅','游泳馆','北航校医院'].map(name=>buildings.find(b=>b.name===name)).filter(Boolean)];
const labelNodes=labelSpecs.map(b=>{const el=document.createElement('span');el.className='map-label'+(b.primary?' primary':'');el.textContent=b.name;$('#labels').append(el);return {b,el};});
const chosenIds=new Set([...$('#place').options].map(o=>o.value));for(const b of buildings){if(chosenIds.has(b.id))continue;const option=document.createElement('option');option.value=b.id;option.textContent=b.name;$('#place').append(option);}
const highlight=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1,1,1)),new THREE.LineBasicMaterial({color:'#628968',transparent:true,opacity:.65}));highlight.visible=false;scene.add(highlight);
let selected=null,tween=null,mode='day',tour=false,top=false,labelsOn=true,lastTime=0,dirty=true;
onInterfaceChange(()=>dirty=true);
const modes={day:{bg:'#e8ede8',sun:'#fff1cd',hemi:2.8,power:3.2,pos:[-230,480,250],exposure:1.3,emission:0,glow:0},sunset:{bg:'#ebe1cf',sun:'#ffb773',hemi:1.7,power:3.9,pos:[-450,180,160],exposure:1.25,emission:.35,glow:.1},night:{bg:'#172a2b',sun:'#a9c7ff',hemi:.65,power:1.1,pos:[-200,430,-100],exposure:1.15,emission:2.8,glow:.5}};
function setMode(value){mode=value;document.body.dataset.mode=value;const m=modes[value];scene.background.set(m.bg);scene.fog.color.set(m.bg);floor.material.color.set(m.bg);sun.color.set(m.sun);sun.intensity=m.power;sun.position.set(...m.pos);hemi.intensity=m.hemi;renderer.toneMappingExposure=m.exposure;materials.lit.emissiveIntensity=m.emission;buildings.filter(b=>b.landmark).forEach(b=>b.glass.emissiveIntensity=m.emission*.12);materials.lamp.emissiveIntensity=m.emission;glowMat.opacity=m.glow;document.body.classList.toggle('night',value==='night');document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===value)));dirty=true;}
function stopTour(){tour=false;controls.autoRotate=false;$('#tour').setAttribute('aria-pressed','false');$('#tour').innerHTML='<span>▷</span> 环游';}
function setTop(v){top=v;$('#top').setAttribute('aria-pressed',String(v));}
function fly(target,position,duration=1200){stopTour();const from=camera.position.clone(),fromTarget=controls.target.clone();tween={start:performance.now(),duration:reduced.matches?0:duration,from,fromTarget,to:new THREE.Vector3(...position),toTarget:new THREE.Vector3(...target)};dirty=true;}
function overview(){$('#selection').hidden=true;$('#selection').open=false;$('#building-search').value='';setTop(false);highlight.visible=false;selected=null;$('#place').value='overview';$('#selection h2').textContent='学院路校区';$('#description').textContent='教学区、宿舍区、家属区、运动场与大运村，按真实地图位置连成完整校园。';$('#accuracy').textContent=buildings.length+' 个建筑轮廓 · 地标细化，其余简化';const target=[-405,0,-170];const k=mobile()?Math.max(1,1.12/camera.aspect):1;fly(target,mobile()?[-405+1100*k,1400*k,-170+1450*k]:[800,1350,1400]);}
const zones={"teaching":{"name":"教学区","target":[-150,0,-445],"pos":[420,700,160]},"north":{"name":"北区","target":[-450,0,-590],"pos":[120,690,50]},"living":{"name":"学生生活区与绿园","target":[-485,0,-340],"pos":[100,650,230]},"family":{"name":"家属区","target":[-830,0,-300],"pos":[-180,700,370]},"sports":{"name":"运动区","target":[-435,0,-10],"pos":[170,670,680]},"dayun":{"name":"大运村与南侧科研区","target":[-470,0,260],"pos":[130,690,900]}};
function selectBuilding(id){if(id.startsWith('zone:')){const z=zones[id.slice(5)];if(!z)return;$('#selection').hidden=false;$('#selection').open=false;$('#place').value=id;selected=null;highlight.visible=false;setTop(false);$('#selection h2').textContent=z.name;$('#description').textContent='选择楼体或搜索名称，查看建筑近景与数据依据。';$('#accuracy').textContent='地图轮廓 · 楼高与细节分级估算';const k=mobile()?1.55:1;fly(z.target,z.pos.map((v,i)=>z.target[i]+(v-z.target[i])*k));return;}if(id==='overview'){overview();return;}if(id==='main'){$('#selection').hidden=false;$('#selection').open=false;$('#place').value=id;selected=null;highlight.visible=false;setTop(false);$('#selection h2').textContent='新主楼';$('#description').textContent='A—G 座依真实轮廓生成；北侧架空连接依据公开照片简化重建。';$('#accuracy').textContent='参考整体 11 层 · 分座层数与连接尺寸待校核';fly([0,8,0],mobile()?[310,380,440]:[250,280,330]);return;}const b=buildings.find(b=>b.id===id)||(id===bridgeBuilding.id?bridgeBuilding:null);if(!b)return;$('#selection').hidden=false;$('#selection').open=false;selected=b;setTop(false);$('#selection h2').textContent=b.name;$('#description').textContent=b.description||(b.main?'保留真实楼体轮廓，窗格、屋顶与立面为简化表达。':'地图轮廓生成的基础体量，屋顶与外观尚未逐栋精细还原。');$('#accuracy').textContent=b.source;$('#place').value=b.id;if(b.id===bridgeBuilding.id)$('#place').value='main';const bb=new THREE.Box3().setFromObject(b.mesh),sz=bb.getSize(new THREE.Vector3()),c=bb.getCenter(new THREE.Vector3());highlight.scale.copy(sz).addScalar(1);highlight.position.copy(c);highlight.visible=true;const d=Math.max(160,Math.max(sz.x,sz.z)*2);if(b.viewFromSouth){fly([b.center[0],9,b.center[1]],[b.center[0]+d*.35,85,b.center[1]+d*.95]);}else if(b.landmark){fly([b.center[0],7,b.center[1]],[b.center[0]-d*.65,75,b.center[1]-d*.95]);}else fly([b.center[0],b.height*.2,b.center[1]],[b.center[0]+d,b.height+d*.9,b.center[1]+d*1.15]);}
for(const b of buildings){const o=document.createElement('option');o.value=b.name;$('#building-names').append(o);}function searchBuilding(){const q=$('#building-search').value.trim();if(!q)return;const b=buildings.find(b=>b.name===q)||buildings.find(b=>b.name.includes(q));if(b){selectBuilding(b.id);$('#building-search').blur();}else toast('未找到建筑，可点击“浏览”查找。');}$('#building-search').addEventListener('change',searchBuilding);$('#building-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchBuilding();}});
$('#place').addEventListener('change',e=>selectBuilding(e.target.value));$('#overview').onclick=overview;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#tour').onclick=()=>{if(tour){stopTour();return;}if(reduced.matches){toast('系统已开启减少动态效果；可拖动模型查看。');return;}tween=null;setTop(false);tour=true;controls.autoRotate=true;$('#tour').setAttribute('aria-pressed','true');$('#tour').innerHTML='<span>Ⅱ</span> 暂停';};
$('#top').onclick=()=>{if(top){overview();return;}setTop(true);let t=controls.target.clone();fly(t.toArray(),[t.x,Math.max(500,camera.position.distanceTo(t)),t.z+.1]);};
$('#north').onclick=()=>{setTop(false);const t=controls.target.clone(),d=camera.position.distanceTo(t);fly(t.toArray(),[t.x,d*.85,t.z+d*.7]);};
function zoom(f){stopTour();tween=null;const offset=camera.position.clone().sub(controls.target);const dist=THREE.MathUtils.clamp(offset.length()*f,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(offset.setLength(dist));controls.update();dirty=true;}
$('#zoom-in').onclick=()=>zoom(.8);$('#zoom-out').onclick=()=>zoom(1.25);
$('#toggle-labels').onclick=()=>{labelsOn=!labelsOn;$('#toggle-labels').setAttribute('aria-pressed',String(labelsOn));$('#labels').style.display=labelsOn?'':'none';};
$('#about').onclick=()=>{stopTour();$('#info').showModal();};$('#info').addEventListener('click',e=>{if(e.target===$('#info')){const r=$('#info').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#info').close();}});
$('#data-count').textContent=`地图获取时间：${DATA.retrievedAt.slice(0,10)}。全校展示范围内绘制 ${buildings.length} 个建筑轮廓，另含照片参考连接；地图完整性与楼高仍需校核。`;
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
$('#download-data').onclick=()=>download(new Blob([JSON.stringify(DATA,null,2)],{type:'application/geo+json'}),'北航全校区地图数据.geojson');
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,2800);}
$('#capture').onclick=()=>{renderer.render(scene,camera);const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;const ctx=c.getContext('2d');ctx.drawImage(renderer.domElement,0,0);const k=c.width/innerWidth;ctx.fillStyle=mode==='night'?'#e7eddc':'#294635';ctx.font=`${20*k}px sans-serif`;ctx.fillText('北航 · 学院路全校区',26*k,38*k);ctx.font=`${10*k}px sans-serif`;ctx.fillText('© OpenStreetMap contributors · ODbL | 真实轮廓 · 楼高与立面简化',26*k,c.height-22*k);c.toBlob(b=>{if(b)download(b,'北航校园-'+mode+'.png')},'image/png');toast('已保存当前视角');};
controls.addEventListener('start',()=>{stopTour();tween=null;setTop(false);});controls.addEventListener('change',()=>dirty=true);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down=[e.clientX,e.clientY,performance.now()];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||performance.now()-down[2]>500){down=null;return;}down=null;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(pickables)[0];if(hit)selectBuilding(hit.object.userData.building.id);});
$('#scene').addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){zoom(.8);e.preventDefault();}if(e.key==='-'){zoom(1.25);e.preventDefault();}if(e.key==='Home'){overview();e.preventDefault();}if(['ArrowLeft','ArrowRight'].includes(e.key)){stopTour();tween=null;const o=camera.position.clone().sub(controls.target).applyAxisAngle(new THREE.Vector3(0,1,0),e.key==='ArrowLeft'?.12:-.12);camera.position.copy(controls.target).add(o);controls.update();e.preventDefault();}});
function resize(){renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();dirty=true;}
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTour();else dirty=true;});reduced.addEventListener('change',()=>{if(reduced.matches)stopTour();});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#loading').style.display='flex';$('#loading').style.opacity=1;$('#loading p').textContent='图形上下文已中断，请刷新页面重试。';});
const debug={ready:false,buildings:buildings.length,get buildingCatalog(){return buildings.map(b=>({id:b.id,name:b.name,center:b.center,height:b.height,source:b.source}))},landmarks:buildings.filter(b=>b.landmark).map(b=>b.name),trees:treePositions.length,errors:[],frameMs:[],get mode(){return mode},get tour(){return tour},get top(){return top},get selected(){return selected?.name},get camera(){return camera.position.toArray()},get calls(){return renderer.info.render.calls},get triangles(){return renderer.info.render.triangles}};window.__campus=debug;
function animate(now){requestAnimationFrame(animate);if(document.hidden)return;const dt=Math.min((now-lastTime)/1000,.05)||.016;lastTime=now;let moving=false;if(tween){const t=tween.duration?Math.min((now-tween.start)/tween.duration,1):1;const e=t*t*(3-2*t);camera.position.lerpVectors(tween.from,tween.to,e);controls.target.lerpVectors(tween.fromTarget,tween.toTarget,e);moving=true;if(t===1)tween=null;}controls.update(dt);if(tour)moving=true;const lim=controls.target;lim.x=THREE.MathUtils.clamp(lim.x,extent[0]-100,extent[2]+100);lim.z=THREE.MathUtils.clamp(lim.z,extent[1]-100,extent[3]+100);
 if(dirty||moving){const start=performance.now();renderer.render(scene,camera);debug.frameMs.push(performance.now()-start);if(debug.frameMs.length>120)debug.frameMs.shift();dirty=false;const theta=controls.getAzimuthalAngle();$('#needle').style.transform=`rotate(${-theta*180/Math.PI}deg)`;const occupied=[],interfaceBounds=getInterfaceBounds();for(const {b,el}of labelNodes){let p=new THREE.Vector3(b.center[0],b.height+10,b.center[1]).project(camera);let x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;let hide=p.z>1||p.z<0||x<20||x>innerWidth-20||y<20||y>innerHeight-45||labelOverlapsInterface(x,y,el,interfaceBounds)||occupied.some(o=>Math.abs(o.x-x)<90&&Math.abs(o.y-y)<25);el.style.visibility=hide?'hidden':'visible';if(!hide){el.style.left=x+'px';el.style.top=y+'px';occupied.push({x,y});}}
 const a=controls.target.clone().project(camera),b=controls.target.clone().add(new THREE.Vector3(50,0,0)).project(camera);let px=Math.hypot((b.x-a.x)*innerWidth/2,(b.y-a.y)*innerHeight/2);if(px<20||px>110){$('#scale-line').style.width='50px';const d=camera.position.distanceTo(controls.target),m=2*d*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/innerHeight*50;$('#scale-text').textContent='约 '+Math.round(m)+' m';}else{$('#scale-line').style.width=px+'px';$('#scale-text').textContent='约 50 m';}}
}
overview();if(tween){camera.position.copy(tween.to);controls.target.copy(tween.toTarget);tween=null;}controls.update();requestAnimationFrame(animate);debug.ready=true;$('#loading').style.opacity=0;setTimeout(()=>$('#loading').style.display='none',550);
}
